// conjugation.js
// Looks up conjugation tables and lemmatizes conjugated forms, reading from
// data sharded by normalized (lowercased, accent-stripped) first letter:
//   data/verbs/<letter>.json  — infinitive -> {template, tenses}
//   data/lemmas/<letter>.json — normalized surface form -> infinitive
// generated by scripts/build-verbiste.js. Each shard is fetched and cached
// at most once per service-worker lifetime, so a lookup only pays for
// ~1/26th of the dataset instead of the whole 6MB+256K-entry index every
// time the service worker wakes from idle.
//
// data/verbs/<letter>.json entries look like:
// {
//   "être": {
//     "template": "être:être",
//     "tenses": {
//       "présent": ["suis", "es", "est", "sommes", "êtes", "sont"],
//       "imparfait": ["étais", "étais", "était", "étions", "étiez", "étaient"],
//       "futur":    ["serai", "seras", "sera", "serons", "serez", "seront"],
//       "passé simple": [...],
//       "conditionnel": [...],
//       "subjonctif présent": [...],
//       "impératif": [...],
//       "participe passé": ["été"],
//       "participe présent": ["étant"]
//     }
//   },
//   ...
// }

const verbShardCache = new Map(); // letter -> { [infinitive]: {template, tenses} }
const lemmaShardCache = new Map(); // letter -> { [normalizedForm]: infinitive }

// Strip accents for lookup key normalization
function normalize(str) {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

// Must match scripts/build-verbiste.js's shardKeyOf exactly, or a word looks
// up a shard that was never built for it.
function shardKeyOf(normalized) {
  return /^[a-z]/.test(normalized) ? normalized[0] : "_other";
}

async function loadShard(cache, dir, key) {
  const cached = cache.get(key);
  if (cached) return cached;

  const url = chrome.runtime.getURL(`data/${dir}/${key}.json`);
  const resp = await fetch(url);
  const data = resp.ok ? await resp.json() : {};
  cache.set(key, data);
  return data;
}

function loadVerbShard(key) {
  return loadShard(verbShardCache, "verbs", key);
}

function loadLemmaShard(key) {
  return loadShard(lemmaShardCache, "lemmas", key);
}

export async function isKnownVerb(word) {
  return (await conjugate(word)) !== null;
}

export async function conjugate(word) {
  const norm = normalize(word);
  const letter = shardKeyOf(norm);

  const verbShard = await loadVerbShard(letter);
  if (verbShard[word]) return { infinitive: word, ...verbShard[word] };

  // Accent/case-insensitive match against infinitives in the same shard
  // (shard assignment is itself accent-insensitive, so the real entry, if
  // any, is guaranteed to be in this shard too).
  const accentMatch = Object.keys(verbShard).find((k) => normalize(k) === norm);
  if (accentMatch) return { infinitive: accentMatch, ...verbShard[accentMatch] };

  // Not an infinitive itself — see if it's a conjugated form of one. The
  // lemma shard is keyed by the SURFACE form's first letter, which is often
  // different from the infinitive's ("vont" → "aller"), so the infinitive
  // this resolves to may live in a different verb shard than the one
  // already loaded above.
  const lemmaShard = await loadLemmaShard(letter);
  const infinitive = lemmaShard[norm];
  if (!infinitive) return null;

  const infLetter = shardKeyOf(normalize(infinitive));
  const infShard = infLetter === letter ? verbShard : await loadVerbShard(infLetter);
  if (!infShard[infinitive]) return null; // shouldn't happen if build output is consistent

  return { infinitive, ...infShard[infinitive] };
}

export const PRONOUNS = ["je", "tu", "il/elle", "nous", "vous", "ils/elles"];
