// conjugation.js
// Looks up conjugation tables and lemmatizes conjugated forms, reading from
// data sharded by normalized (lowercased, accent-stripped) first letter:
//   data/verbs/<letter>.json  — infinitive -> {template, tenses}
//   data/lemmas/<letter>.json — normalized surface form -> infinitive
// generated by scripts/build-verbiste.js. Each shard is fetched and cached
// at most once per service-worker lifetime, so a lookup only pays for
// ~1/26th of the dataset instead of the whole 6MB+256K-entry index every
// time the service worker wakes from idle.
//
// data/verbs/<letter>.json entries look like:
// {
//   "être": {
//     "template": "être:être",
//     "tenses": {
//       "présent": ["suis", "es", "est", "sommes", "êtes", "sont"],
//       "imparfait": ["étais", "étais", "était", "étions", "étiez", "étaient"],
//       "futur":    ["serai", "seras", "sera", "serons", "serez", "seront"],
//       "passé simple": [...],
//       "conditionnel": [...],
//       "subjonctif présent": [...],
//       "impératif": [...],
//       "participe passé": ["été"],
//       "participe présent": ["étant"]
//     }
//   },
//   ...
// }

const verbShardCache = new Map(); // letter -> { [infinitive]: {template, tenses} }
const lemmaShardCache = new Map(); // letter -> { [normalizedForm]: infinitive }

// Strip accents for lookup key normalization
function normalize(str) {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

// Must match scripts/shard-writer.js's shardKeyOf exactly (also duplicated in
// background/lexicon.js, for the same reason) — or a word looks up a shard
// that was never built for it.
function shardKeyOf(normalized) {
  return /^[a-z]/.test(normalized) ? normalized[0] : "_other";
}

// fetch() against our own bundled chrome-extension:// resources can throw a
// raw "TypeError: Failed to fetch" — not resp.ok === false, an actual thrown
// error — in the moment right after the service worker wakes from idle and
// its resource loader isn't warmed up yet. Uncaught, that error propagated
// through conjugate()/isKnownVerb() to service-worker.js's generic handler
// and came out the other end as a cryptic "Failed to fetch" wherever a lookup
// happened to be in flight — including LOOKUP_WORDS, which annotator.js calls
// on every page scan, so this was the likely repeat offender. One retry after
// a short delay clears the transient case; a real failure still degrades to
// an empty shard (treated as "no data for this letter") rather than throwing.
async function fetchJsonWithRetry(url) {
  for (let attempt = 0; ; attempt++) {
    try {
      const resp = await fetch(url);
      return resp.ok ? await resp.json() : {};
    } catch (err) {
      if (attempt > 0) {
        console.error("[FLA conjugation] failed to load", url, err);
        return {};
      }
      await new Promise((r) => setTimeout(r, 200));
    }
  }
}

async function loadShard(cache, dir, key) {
  const cached = cache.get(key);
  if (cached) return cached;

  const url = chrome.runtime.getURL(`data/${dir}/${key}.json`);
  const data = await fetchJsonWithRetry(url);
  cache.set(key, data);
  return data;
}

function loadVerbShard(key) {
  return loadShard(verbShardCache, "verbs", key);
}

function loadLemmaShard(key) {
  return loadShard(lemmaShardCache, "lemmas", key);
}

export async function isKnownVerb(word) {
  return (await conjugate(word)) !== null;
}

export async function conjugate(word) {
  const norm = normalize(word);
  const letter = shardKeyOf(norm);

  const verbShard = await loadVerbShard(letter);
  if (verbShard[word]) return { infinitive: word, ...verbShard[word] };

  // Accent/case-insensitive match against infinitives in the same shard
  // (shard assignment is itself accent-insensitive, so the real entry, if
  // any, is guaranteed to be in this shard too).
  const accentMatch = Object.keys(verbShard).find((k) => normalize(k) === norm);
  if (accentMatch) return { infinitive: accentMatch, ...verbShard[accentMatch] };

  // Not an infinitive itself — see if it's a conjugated form of one. The
  // lemma shard is keyed by the SURFACE form's first letter, which is often
  // different from the infinitive's ("vont" → "aller"), so the infinitive
  // this resolves to may live in a different verb shard than the one
  // already loaded above.
  const lemmaShard = await loadLemmaShard(letter);
  const infinitive = lemmaShard[norm];
  if (!infinitive) return null;

  const infLetter = shardKeyOf(normalize(infinitive));
  const infShard = infLetter === letter ? verbShard : await loadVerbShard(infLetter);
  if (!infShard[infinitive]) return null; // shouldn't happen if build output is consistent

  return { infinitive, ...infShard[infinitive] };
}

export const PRONOUNS = ["je", "tu", "il/elle", "nous", "vous", "ils/elles"];

// Resolves a saved word to the key its SRS card should live under. Verb
// forms collapse onto their infinitive ("mangeons" -> "manger") so the same
// verb reviewed in different tenses is one card, not several. There's no
// general-purpose lemmatizer yet (Lexique-derived data/lexicon.json is
// Phase 2), so anything conjugate() doesn't recognize falls back to its own
// normalized surface form. Case only, not accents: French accents are
// meaning-bearing (ou/où, a/à), so stripping them would wrongly merge
// distinct words into one card.
export async function resolveLemma(word) {
  const table = await conjugate(word);
  if (table) return table.infinitive;
  return word.trim().toLowerCase();
}
