// lexicon.js
// Looks up POS/gender/number/frequency-rank for arbitrary French words, and
// checks a word against the bundled cognate list. Mirrors conjugation.js's
// shard-cache pattern:
//   data/lexicon/<letter>.json — surface form -> {lemma, pos, gender, number, freqRank}
//   data/cognates.json         — French word -> English cognate spelling (single file, small)
// generated by scripts/build-lexicon.js (lexicon.json is hand-curated for
// cognates.json — see CLAUDE.md's Data bundles section).

const lexiconShardCache = new Map(); // letter -> { [mot]: {lemma,pos,gender,number,freqRank} }
let cognatesCache = null; // whole data/cognates.json, fetched once

// Must match scripts/shard-writer.js's normalize()/shardKeyOf() exactly (and
// background/conjugation.js's copy), or a word looks up a shard that was
// never built for it.
function normalize(str) {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

function shardKeyOf(normalized) {
  return /^[a-z]/.test(normalized) ? normalized[0] : "_other";
}

async function loadLexiconShard(key) {
  const cached = lexiconShardCache.get(key);
  if (cached) return cached;

  const url = chrome.runtime.getURL(`data/lexicon/${key}.json`);
  const resp = await fetch(url);
  const data = resp.ok ? await resp.json() : {};
  lexiconShardCache.set(key, data);
  return data;
}

async function loadCognates() {
  if (cognatesCache) return cognatesCache;
  const url = chrome.runtime.getURL("data/cognates.json");
  const resp = await fetch(url);
  cognatesCache = resp.ok ? await resp.json() : {};
  return cognatesCache;
}

// Lowercase-only key — never accent-fold, same rationale as
// conjugation.js#resolveLemma: French accents are meaning-bearing (a/à, ou/où).
export async function lookupWord(word) {
  if (!word || /\s/.test(word.trim())) return null; // phrases/sentences never match
  const key = word.toLowerCase();
  const shard = await loadLexiconShard(shardKeyOf(normalize(key)));
  return shard[key] || null;
}

// Batch form: loads each needed shard once regardless of how many words map
// to it, so a page with hundreds of unique words costs one fetch per letter,
// not one per word.
export async function lookupWords(words) {
  const shardKeys = new Set(
    words.filter((w) => w && !/\s/.test(w.trim())).map((w) => shardKeyOf(normalize(w.toLowerCase())))
  );
  await Promise.all([...shardKeys].map(loadLexiconShard));

  const out = {};
  for (const word of words) out[word] = await lookupWord(word);
  return out;
}

export async function lookupCognate(word) {
  if (!word) return null;
  const table = await loadCognates();
  return table[word.toLowerCase()] || null;
}

// Composite used by the LOOKUP_WORDS message handler: one round trip for
// both the lexicon entries and any cognate hits. `cognates` is sparse (only
// true hits) to keep the response small for pages with hundreds of words.
export async function annotateWords(words) {
  const [entries, cognatesTable] = await Promise.all([lookupWords(words), loadCognates()]);
  const cognates = {};
  for (const word of words) {
    const hit = cognatesTable[word.toLowerCase()];
    if (hit) cognates[word] = hit;
  }
  return { entries, cognates };
}
